In [1]:
#Lab Task 01
import numpy as np
arr=np.array([[0,1],[2,3]])
print("Original array:")
print(arr)
flatarr=arr.flatten()
print("Flattened array:")
print(flatarr)
max=flatarr.max()
min=flatarr.min()
print("Maximum value of the flattened array:",max)
print("Minimum value of the flattened array:",min)


Original array:
[[0 1]
 [2 3]]
Flattened array:
[0 1 2 3]
Maximum value of the flattened array: 3
Minimum value of the flattened array: 0


In [2]:
#Lab Task 02
import numpy as np
matrix=np.arange(2,11).reshape(3,3)
print("3x3 Matrix with values from 2 to 10:")
print(matrix)


3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
#Lab Task 03
import numpy as np
arr=np.array([1,2,3,4])
print("Original array:",end='')
print(arr)
floatarr=arr.astype(float)
print("Array converted to a float type:",end='')
print(floatarr)


Original array:[1 2 3 4]
Array converted to a float type:[1. 2. 3. 4.]


In [4]:
#Lab Task 04
import numpy as np
M1=np.array([[5,5],[1,2]])
M2=np.array([[0,1],[1,0]])
print("Matrix M1:")
print(M1)
print("Matrix M2:")
print(M2)
result=np.dot(M1,M2)
print("(M1×M2):")
print(result)
transpose=result.T
print("Transpose of (M1xM2):")
print(transpose)



Matrix M1:
[[5 5]
 [1 2]]
Matrix M2:
[[0 1]
 [1 0]]
(M1×M2):
[[5 5]
 [2 1]]
Transpose of (M1xM2):
[[5 2]
 [5 1]]


In [5]:
#Lab Task 05
import numpy as np
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print("Original matrix A:")
print(A)
det=np.linalg.det(A)
print("Determinant of A:",det)
A_inv=np.linalg.inv(A)
np.set_printoptions(precision=8,suppress=True)
print("Inverse of matrix A:")
print(A_inv)


Original matrix A:
[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
Determinant of A: -1309.0000000000005
Inverse of matrix A:
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
